"""empty message

Revision ID: df8ea80161db
Revises: e5ca251e403e
Create Date: 2022-05-10 12:22:39.982142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8ea80161db'
down_revision = 'e5ca251e403e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('picture', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'picture')
    # ### end Alembic commands ###
