"""empty message

Revision ID: cc1abfe057d5
Revises: df8ea80161db
Create Date: 2022-05-13 15:09:23.892433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1abfe057d5'
down_revision = 'df8ea80161db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'quantity')
    # ### end Alembic commands ###
